//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConectarDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class documento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public documento()
        {
            this.indice_pagina_documento = new HashSet<indice_pagina_documento>();
        }
    
        public int docu_id { get; set; }
        public string docu_name { get; set; }
        public string docu_description { get; set; }
        public string docu_author_full_name { get; set; }
        public string docu_author_email { get; set; }
        public string docu_serial_code { get; set; }
        public Nullable<System.DateTime> docu_created_at { get; set; }
        public Nullable<System.DateTime> docu_updated_at { get; set; }
        public Nullable<System.DateTime> docu_deleted_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<indice_pagina_documento> indice_pagina_documento { get; set; }
    }
}
