//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConectarDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class indice_pagina_documento
    {
        public int index_id { get; set; }
        public int docu_id { get; set; }
        public string index_name { get; set; }
        public int index_page { get; set; }
        public System.DateTime index_created_at { get; set; }
    
        public virtual documento documento { get; set; }
    }
}
